spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  messages:
#    basename: messages
#    encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /socks-store